display_name: Thank You, Raul Grijalva and Keith Ellison, for Endorsing Bernie Sanders
domainroot: http://tyraul.readytofight.org/

meta:
  title: Thank You, Raul and Keith!
  description: "Rep. Grijalva and Keith Ellison just endorsed Bernie Sanders for President, now he's
  sure to take a lot of heat. Let him know we've got his back!"
  keywords: Grijalva Sanders Endorsement
  fb_description: "Rep. Grijalva and Keith Ellison just endorsed Bernie Sanders for President, they'er
  sure to take a lot of heat. Let them know we've got their backs!"
  fb_site_name: Thank You, Raul Grijalva and Keith Ellison, for endorsing Bernie Sanders!
  fb_title: Thank you, Raul and Keith

footer:
  copyright: "do whatever you want with this site's content, as long
  as you #FeelTheBern"
  mailto_subject: "Get Grijalva and Ellison's back -- say thanks for endorsing Bernie"
  twitter_message: "I just signed the card to thank @RepRaulGrijalva for having @BernieSanders back. Add your name: http://tyraul.readytofight.org @Ready2FightBack"

exclude:
  - Gruntfile.js
  - scss
  - .ruby-version
  - package.json
  - README.md
  - node_modules
  - bower_components
  - .sass-cache
  - CNAME
