display_name: Thank You, Raul Grijalva, for Endorsing Bernie Sanders
domainroot: http://tyraul.snook.pub/

meta:
  title: Thank You, Raul!
  description: "Rep. Grijalva just endorsed Bernie Sanders for President, now he's
  sure to take a lot of heat. Let him know we've got his back!"
  keywords: Grijalva Sanders Endorsement
  fb_description: "Rep. Grijalva just endorsed Bernie Sanders for President, now he's
  sure to take a lot of heat. Let him know we've got his back!"
  fb_site_name: Thank You, Raul Grijalva, for endorsing Bernie Sanders!
  fb_title: Thank you, Raul

footer:
  copyright: "do whatever you want with this site's content, as long
  as you #FeelTheBern"
  mailto_subject: "Get Grijalva's back -- say thanks for endorsing Bernie"
  twitter_message: "I just signed the card to thank @RepRaulGrijalva for having @BernieSanders back. Add your name: http://tyraul.snook.pub/ @Ready2FightBack"

exclude:
  - Gruntfile.js
  - scss
  - .ruby-version
  - package.json
  - README.md
  - node_modules
  - bower_components
  - .sass-cache
  - CNAME
